### ISSUE TITLE
Tinker's Smeltery raise error

### ISSUE THREAD

**Issue by EarlyZ-LK** [Sefiraat/SlimeTinker#123]
## Description

An Error occurred while trying to create a BlockMenu

![image](https://user-images.githubusercontent.com/77195953/152292785-e2c1a7d4-cf02-4837-a6d4-3892e51d230a.png)

## Server Log / Error Report

https://pastebin.com/kBWfqSfc

## Environment

- Minecraft Version: git-Paper-408 (MC: 1.17.1)
- CS-CoreLib Version: 
- Slimefun Version: Slimefun DEV - 999
- Plugin Version: SlimeTinker vDEV - 65

![image](https://user-images.githubusercontent.com/77195953/152291956-38799b99-5974-4e33-be47-68f0c01c19a7.png)

**Comment by ybw0014** [comment]
Can you provide information about how to replicate this?

**Comment by EarlyZ-LK** [comment]
> Can you provide information about how to replicate this?

tbh I don't know 
its spamming the console so I decided to report it 

https://pastebin.com/5itL4Vyk
