### ISSUE TITLE
Issue with making tools

### ISSUE THREAD

**Issue by ThunderIsBest** [Sefiraat/SlimeTinker#124]
My friend has server. It's just a small survival with people, he knows from real life. 
He started making Tinkery machines and stuff. Machines work properly. But...
When it comes to making tools in Tinker's Tool Table, that's where he finds an issue.
He tried to make a tool (Axe) out of Steel and now even from Brass (the only part that was Brass was Axe head, he said that he thinks everything else was from Steel) and both of those things, when he tries to create it don't work. The table vanishes and puts itself back into his inventory, now just as Smithing Table with a name.

## Server Log / Error Report

It's as a file here, since I don't know how to make a pastebin thing.

## Environment (Required)

- Minecraft Version: 1.18.1
- Slimefun Version: RC 30
- Plugin Version: DEV 65
[slimefun error.txt](https://github.com/Sefiraat/SlimeTinker/files/7998557/slimefun.error.txt)
![2022-02-03_22 57 43](https://user-images.githubusercontent.com/57209687/152436219-ba56cc84-b62f-4e39-856d-dc6abcde1f0d.png)

**Comment by Sefiraat** [comment]
What was the Binder you were using?
And can you pass the file located here: /plugins/Slimefun/error-reports/

**Comment by ThunderIsBest** [comment]
[error file.zip](https://github.com/Sefiraat/SlimeTinker/files/7998638/error.file.zip)

Cast: Mail Links and apparently it was from Brass.

**Comment by Sefiraat** [comment]
Found the issue, fix incoming :)
It would seem you aren't using the correct item for a Tool binding - you might want to run through the guide to look for bindings - string is the most basic binding you can make.

**Comment by ThunderIsBest** [comment]
1. Yeah... we found out xD Now it works totally fine after doing the right binding tool :D
