### ISSUE TITLE
I can't make casts

### ISSUE THREAD

**Issue by RYHN122** [Sefiraat/SlimeTinker#13]
i can't make any casts, it always says, "The selected metal cannot be shaped into the selected cast"
i was trying to make a zinc rod

**Comment by Sefiraat** [comment]
As i mentioned in discord, ill need some screenshots to help me out here, what metals are in the tank, whats in the Smeltery GUI and ill need startup logs

**Comment by Sefiraat** [comment]
Fixed in Build#15 :)
