### ISSUE TITLE
Make modifications configurable

### ISSUE THREAD

**Issue by Auxority** [Sefiraat/SlimeTinker#151]
### Description

Hi there,

I would like modifications on SlimeTinker tools to be configurable.
Just like some metal traits, some modifications might be too overpowered on certain servers.
It would be nice to get the ability to fully disable/enable a modification, change the required items per level, how many levels each modification has and what the increase in percentage is for each level.
But just starting with being able to enable or disable certain modifications through a configuration file would be great.

**Comment by Sefiraat** [comment]
This is on the cards for the rewrite, SlimeTinker2, which is a good... 40%? completed give or take ha. Very good idea and it is one that is coming

**Comment by Auxority** [comment]
Glad to hear that it is being added. Great work!
