### ISSUE TITLE
Allow disabling compat. with other addons, or certain alloys/metals altogether (I don't need Liquid Love, whatever the heck that is.)

### ISSUE THREAD

**Issue by MagmaBro123** [Sefiraat/SlimeTinker#152]
### Description

Title.

Allow disabling metals/materials we don't want.

### Preview

An example config:

SLIMEFUN:
Liquid-love: true

etc.

**Comment by ybw0014** [comment]
you can disable traits that you don't want in traits.yml

**Comment by MagmaBro123** [comment]
I did. Stuff like Liquid Love is still enabled.

**Comment by Sefiraat** [comment]
Within this current version, disabling traits is the best we have. I appreciate your comments and within the next iteration I will ensure more granularity is present for removing metals/traits.
