### ISSUE TITLE
Ores don’t like linkers

### ISSUE THREAD

**Issue by Lagcatalyst** [Sefiraat/SlimeTinker#160]
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

Magnonium tool rod plus fortune sing pickaxe rod makes ores disappear dropping nothing

### Steps to reproduce

Magnonium rod
Fortune sing pickaxe

### Expected behavior

Litterly nothing

### Server software

Spigot

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

Recent

### SlimeTinker version

Recent

### Other plugins

Infinity expansion

**Comment by ybw0014** [comment]
latest/recent is not a valid version number, please provide exact ones.

**Comment by Sefiraat** [comment]
Yes, please provide your version of… linkers. Lul :)

**Comment by ybw0014** [comment]
No response for 1 month, closing. Feel free to provide required information and reopen this issue.
