### ISSUE TITLE
bulky trait dropping relics of cthonia on mining

### ISSUE THREAD

**Issue by Ritwik-main** [Sefiraat/SlimeTinker#168]
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

relics of cthonia shouldnt drop when mined. but when exploded with a pickaxe with bulky trait, it drops the relic

### Steps to reproduce

1.get a tinker pickaxe with bulky trait.(reinforced alloy)
2.place a relic of cthonia from sefi's relics of cthonia
3.break a block next to the relic so the bulky trait breaks the relic and allows us to pick it up

### Expected behavior

relics shouldnt drop on mining

### Server software

Paper

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

1047

### SlimeTinker version

77

**Comment by Sefiraat** [comment]
Heya Ritwik,
We just extend Explosive Tool here to it'll need to be resolved by either listening to the event or checking for the tool itself. It would also indicate this is an issue with explosive tools from Slimefun as well as fluffy.
