### ISSUE TITLE
tinkers workbench steals buckets after making cheese

### ISSUE THREAD

**Issue by pHI10S0PH3RKING** [Sefiraat/SlimeTinker#17]
Used the tinkers workbench to make cheese recipe took milk bucket and salt and returned cheese in the output as expected but did not return empty bucket. confirmed with enhanced crafting table and enhanced autocrafter both returned empty buckets.  installed version is minecraft 1.16.5-R0.1-Snapshot slimefun dev 929. tested live version on tantrum server.

**Comment by Sefiraat** [comment]
Damn, who knew the table was such a thief!
I'll have words with it shortly and make sure it knows it's place...

**Comment by ybw0014** [comment]
So this is the InfinityLib thing right now.
