### ISSUE TITLE
Hope to support 1.20.1

### ISSUE THREAD

**Issue by bananaQwQ666** [Sefiraat/SlimeTinker#179]
### Description

Recently, the server version has been upgraded to 1.20.1, but the plugin is currently unable to run on 1.20.1. We hope to adapt it as soon as possible

**Comment by Sefiraat** [comment]
Can you let me know what doesn’t work on 1.20.1. As far as I know it should be fully working. If you can forward me any specific errors you get or other possible information including Slimefun versions etc. that would be most helpful.

**Comment by bananaQwQ666** [comment]
I don't know what the reason is now, but I downloaded Slimetinker again and it seems to be running. I think this may be due to issues with previous files, sorry

**Comment by Sefiraat** [comment]
So long as it’s all working! Hope you enjoy it :)
