### ISSUE TITLE
Console warning  Plugin 'SlimeTinker' is creating timing 'Commands' - this is deprecated behavior, please report it to the authors: Sefiraat

### ISSUE THREAD

**Issue by MomaCods** [Sefiraat/SlimeTinker#189]
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

This is on 1.20.2 the below table doesnt have that as an option

### Steps to reproduce

I switched from Spigot 1.20.1 to Paper 1.20.2 and these warnings came up
![Console Error](https://github.com/Sefiraat/SlimeTinker/assets/17677132/73d069e3-5eea-4cc4-b0dc-8e511ce64cf5)

### Expected behavior

I was expecting no errors or warnings in console as there had previously been none

### Server log

https://pastebin.com/dKFG2UGf

### Error report

https://pastebin.com/dKFG2UGf

### Server software

Paper

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

Slimefun4 - DEV 1104 (git c9774)

### SlimeTinker version

SlimeTinker - DEV 84 (git 2c9f6)

### Other plugins

chat emojis, pyro lib, LuckPerms, Vanish, ProtocolLib, SimpleRtp, Vault, Holomob Health, World Edit, EssentialsX, PyroFishing, EssentialsChat, LWC, EssentialsProtect, Essentials AntiBuild, EssentialsSpawn, Chat Manager, Core Protect, Wild Stacker, ExtraStorage, GriefDefender, Graves, Quests, as well as SF Addons SFchunkInfo, ExtraGear, SFadvancement,SlimeHUD,SFCalc, MobCapturer, TransEndence, HotBar PEts, Exotic Garden, ExtraTools, Relics of Cthonia, SimpleMaterialGenerators, DyeBench, Supreme, VillagerUtils, Whatisthis, SlimyTreeTaps, FlowerPower, FluffyMachines, DyedBackPacks, LiteExpansion, InfinintyExpansion,NEtworks,DynaTech,Slimetinker

**Comment by ybw0014** [comment]
no need to worry about

**Comment by MomaCods** [comment]
Ok thanks lol

Didn't want to ignore it .. when it told me to tell you lol
