### ISSUE TITLE
Tinkers workbench cant upgrade exotic garden plant

### ISSUE THREAD

**Issue by pHI10S0PH3RKING** [Sefiraat/SlimeTinker#19]
## Description (Required)

Placed correct recipe for upgrading gold plant to Redstone plant in the tinkers workbench and no result was shown in the output, pressing the crafting button gave no output.
## Steps to reproduce the Issue (Required) 
place gold plant in the center square and redstone blocks above, below, and to each side forming a cross pattern in the tinkers workbench and click craft to get no result. do the same on a standard enhanced crafting table and get a redstone plant. 
![image](https://user-images.githubusercontent.com/85084869/125567674-8f3ec84c-ce38-4e95-bb38-0023ab132f89.png)

## Expected behavior (Required)

craft a redstone plant from the recipe provided
## Server Log / Error Report
no report i can access as i am a player on the server

## Environment (Required)

(live on tantrum server) java minecraft 1.16.5-r0.1-snapshot slimefun dev-929 (git d39a5c1b)
 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version:

**Comment by jigglypuff2731** [comment]
uhh i think this isnt supposed to craft non tinker items

**Comment by ybw0014** [comment]
Just tested crafting redstone plant and some other magical plants, all work fine, so I will close this issue. Feel free to reopen it.
