### ISSUE TITLE
Hates 1.20.2, 3, and 4. Please update.

### ISSUE THREAD

**Issue by MagmaBro123** [Sefiraat/SlimeTinker#195]
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

Title.

(Pufferfish)

### Steps to reproduce

Use this and Slimefun on a Paper 1.20.2, 3 or 4 server.

### Expected behavior

The plugin to load.

### Server log

https://pastebin.com/PeQ3AfRD

### Error report

See above.

### Server software

Other (please specify in your description)

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

![2024-01-14_17 56 43](https://github.com/Sefiraat/SlimeTinker/assets/51277766/851526c3-ead5-4e83-a4fa-48184e25d33a)
![2024-01-14_17 56 45](https://github.com/Sefiraat/SlimeTinker/assets/51277766/d9152d09-ddb9-4bb4-8cc7-7faab5662922)

### SlimeTinker version

See above.

### Other plugins

Tested with and without other plugins. However, this erroring on an updated version shouldn't be caused by other stuff.

You also have 10 PRs. Please go look at them.

**Comment by ybw0014** [comment]
already fixed. as SlimeTinker isnt on blob builds yet, you will need to compile the latest version by yourself, or wait for Sefi to migrate.

**Comment by MagmaBro123** [comment]
I have no idea how to compile plugins.
