### ISSUE TITLE
slimetinker doesn't load in 1.20.4

### ISSUE THREAD

**Issue by Boomer-1** [Sefiraat/SlimeTinker#210]
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

here's the error in the console log for dev6

09.08 22:55:42 [Server] ERROR Error occurred while enabling SlimeTinker vDev - 6 (Is it up to date?)
09.08 22:55:42 [Server] INFO java.lang.ExceptionInInitializerError: null
09.08 22:55:42 [Server] INFO at io.github.sefiraat.slimetinker.items.tinkermaterials.TinkerMaterialManager.<init>(TinkerMaterialManager.java:118) ~[SlimeTinker.jar:?]
09.08 22:55:42 [Server] INFO at io.github.sefiraat.slimetinker.SlimeTinker.onEnable(SlimeTinker.java:74) ~[SlimeTinker.jar:?]
09.08 22:55:42 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
09.08 22:55:42 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
09.08 22:55:42 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
09.08 22:55:42 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
09.08 22:55:42 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.getItem()" because the return value of "io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.getById(String)" is null
09.08 22:55:42 [Server] INFO at io.github.sefiraat.slimetinker.items.tinkermaterials.setup.TinkersMaterialsDynatech.<clinit>(TinkersMaterialsDynatech.java:21) ~[SlimeTinker.jar:?]

### Steps to reproduce

start server with slimetinker installed

### Expected behavior

slimetinker to load.

### Server log

see above

### Error report

see above

### Server software

Paper

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

1149

### SlimeTinker version

dev 6

**Comment by ybw0014** [comment]
update dynatech to 33

**Comment by Boomer-1** [comment]
looks like that did it, thanks
