### ISSUE TITLE
Heavy Trait doesnt check if there is an unbreaking enchant

### ISSUE THREAD

**Issue by TerslenK** [Sefiraat/SlimeTinker#27]
## Description (Required)
I added my SlimeTinker pick heavy trait and have unbreaking 10 enchant in it but it doesnt check there is an unbreaking enchant

## Expected behavior (Required)
i thinked that it would check if there was an unbreaking enchant

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version:

**Comment by Sefiraat** [comment]
Current how it's meant to be - open to the idea of working unbreaking into it. Ill think on it!

**Comment by Sefiraat** [comment]
I’ve not heard more about this and I’m roughly happy with how it is so, for now, I’ll leave this as-is :)
