### ISSUE TITLE
Typo and suggestion

### ISSUE THREAD

**Issue by ybw0014** [Sefiraat/SlimeTinker#29]
## Typo

[Here](https://github.com/Sefiraat/SlimeTinker/blob/master/src/main/java/io/github/sefiraat/slimetinker/items/Materials.java#L813) is the typo:
![typo](https://cdn.discordapp.com/attachments/871729538302877736/871729725154930758/unknown.png)

The typo should be corrected with iridium nugget.

## Suggestion

Similar to Slimefun/Slimefun4#3191, the background would better use ChestMenuUtils#getBackground() to support the custom resource pack.

[Here](https://github.com/Sefiraat/SlimeTinker/blob/master/src/main/java/io/github/sefiraat/slimetinker/utils/GUIItems.java#L22)

**Comment by Sefiraat** [comment]
Both added to the Armour update, thanks!
