### ISSUE TITLE
Tinkers dupe

### ISSUE THREAD

**Issue by pump61** [Sefiraat/SlimeTinker#30]
[https://youtu.be/JipiVKVpRHE](url)

 - Minecraft Version: 1.17.1 purpur
 - Slimefun Version: Slimefun DEV - 958
 - Plugin Version: SlimeTinker vDEV - 22 (git 9004e1f2)

**Comment by Sefiraat** [comment]
Fixed in build 22. Your video was from 21 (thanks, it helped me fix it 👍 )
