### ISSUE TITLE
 Could not pass event InventoryClickEvent to Slimefun vDEV - 960 (git 0df4694a)

### ISSUE THREAD

**Issue by thefirstmine** [Sefiraat/SlimeTinker#37]
## Description (Required)

Server keeps showing this error on console when trying to use a repair bench.

## Steps to reproduce the Issue (Required)

Get a repair bench
Try and repair an item using a repair kit.

## Expected behavior (Required)

Tool gets repaired.

## Server Log / Error Report

https://pastebin.com/ZM4wsm47

## Environment (Required)

 - Minecraft Version: 1.17.1 Paper-107
 - CS-CoreLib Version: N/A
 - Slimefun Version: vDEV - 960
 - Plugin Version: vDEV - 26

**Comment by Sefiraat** [comment]
This error happens when using /sf cheat for repair kits or parts. Unfortunately due to the way I generate parts /sf cheat and /sf give will not work correctly :(

**Comment by Sefiraat** [comment]
I've not heard more to confirm it is /sf cheat or if it isn't with more info so ill close this for now. Feel free to open if it is something else :)
