### ISSUE TITLE
not able to add reinforced modification 

### ISSUE THREAD

**Issue by eenderrGamer** [Sefiraat/SlimeTinker#53]
## Description (Required)
I have made a tinker tool sword and I have modifiers left but when I try to add the reinforced modification in the station it says put in a valid item I've tried reinforced plates and obsidian neither of them work

![2021-09-04_13 33 59](https://user-images.githubusercontent.com/90109858/132104757-98eab29b-0a04-4d7c-8443-065234f92d36.png)
![2021-09-04_13 34 49](https://user-images.githubusercontent.com/90109858/132104759-1573e317-ed65-4e34-a96a-e756672c75c4.png)

**Comment by Sefiraat** [comment]
The mod requires the specific plate located in the guide under SlimeTinker - Materials
