### ISSUE TITLE
SlimeTinker armor with locked tool can dupe blocks

### ISSUE THREAD

**Issue by ybw0014** [Sefiraat/SlimeTinker#62]
## Description (Required)

When wearing Tinker's armor and use a locked tool to break blocks, the block is still here and generates drops.
Without Tinker's armor, there are no drops.

## Steps to reproduce the Issue (Required)

Video: https://youtu.be/QXXgD1sieo8

1. Make any piece of Tinker's armor.
2. Get a locked tool from `/sf cheat` or someone else (usually from shop). Here I get a cobalt pickaxe.
3. Wear that piece of armor, and break any block.
4. Some blocks will generate drops.

Some server owners sent me vids that they can dupe shulker boxes and chests, but I cannot reproduce that.

## Expected behavior (Required)

No drops.

## Server Log / Error Report

No error log in console.

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version:
 - Slimefun Version: 971
 - Plugin Version: 36

Only Slimefun and SlimeTinker are installed.

**Comment by Sefiraat** [comment]
Nice find. Let me know if you need help - I have tested annotating to LOWEST and ignoreCancelled and this still happens so, unless i'm missing something, we may need to check for SlimefunItem#canUse() directly?

**Comment by ybw0014** [comment]
Looks like it is fixed in build 37, so I will close this issue.

**Comment by Sefiraat** [comment]
Oh damn I must have screwed up my branches as my testing was not meant to be in that push, I wasn’t overly happy with what I did, if you have anything close to a better implementation feel free to change it >_< this is why I should rush crap out during my breaks. Sorry.

**Comment by ybw0014** [comment]
Fine, but I will still make pull requests first.
