### ISSUE TITLE
Tinker's Workbench turns any and all Magical Essence into dirt

### ISSUE THREAD

**Issue by ReasonFoundDecoy** [Sefiraat/SlimeTinker#79]
1. Obtain any Magical Essence type, you can even mix-and-match different types
2. Put Essences into the Tinker's Workbench around the outside of the crafting area
3. Click "Craft", see Dirt result
![](https://cdn.discordapp.com/attachments/881906190085390377/905806437886869544/unknown.png)
![](https://cdn.discordapp.com/attachments/881906190085390377/905806512046362624/unknown.png)

Video of process: https://kapwi.ng/c/O3j-pc87Jl

**Comment by Sefiraat** [comment]
Sigh, you do bring me the fun bugs Reason ;)!
Ill take a look asap :)
