### ISSUE TITLE
Tools durability vs plugins

### ISSUE THREAD

**Issue by kmethex** [Sefiraat/SlimeTinker#8]
The axe is completely destroyed-deleted from inventory when used with a special ability from the plugin AureliumSkills and FreeRPG for fast and complete tree felling

Plugins:

https://www.spigotmc.org/resources/aurelium-skills-advanced-skills-stats-abilities-and-more.81069/

https://www.spigotmc.org/resources/freerpg-1-15-1-16-5.81954/

 - Minecraft Version: 1.17
 - Slimefun Version: SF4 - DEV 939 (git 57f75)
 - Plugin Version: SlimeTinker - DEV 8 (git d5154)

**Comment by Sefiraat** [comment]
So, looking through the code for FreeRPG. The plugin manually damages the tool and breaks it as part of the skill which is something I cant detect nor do anything about. 
There isn't too much to be done here if the plugin isn't using PlayerItemDamageEvent to change the durability so I think either dont use Tinkers tools with FreeRPG or the plugins are, at the moment, incompatible.
