### ISSUE TITLE
not be able to craft some of the tinkers armor/stuff

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/SlimeTinker#81]
hey again guess who!?
as u know there is sth wrong with crafting mail links with ghostly essen.. and of course Redstone alloy ingot
as I know , not sure about other stuff yet 

and I got some suggestions and questions too
1-where is boomerite ingot I can find the molten recipe but no actual recipe is there for it
2-whats the use of all this leveling for nothing for example a piece of armor after 10 its useless
or even a sword after 50 and does nothing not even give it a small buff like after each level of armor it increases the defence by 1%
3-plz add some modifications as well it would really be great we kill our selves to get the armor and up it but not really much after it

**Comment by ybw0014** [comment]
can confirm this bug
for suggestions, you should post them in a separate issue. the issue template was fixed after you post this issue here, you can now post them.
for questions, you can ask them in Slimefun discord #other-addons, or Slimefun Addon Community discord #slime-tinker.

**Comment by Sefiraat** [comment]
Found the issue (I think) ill fix/test and ship during lunch today.

As for Boomerite, it is ONLY craftable by alloying in the first instance.

And yes, follow YB's advice around suggestions. An issue should be just one single thing to be worked on and completed :)
