### ISSUE TITLE
mcMMO Mining Double Drops Not Working

### ISSUE THREAD

**Issue by iLuckyx** [Sefiraat/SlimeTinker#88]
## Description (Required)

When mining with SlimeTinker armor on, mcMMO mining double drops no longer drop. 

## Steps to reproduce the Issue (Required)

Unlock the mcMMO double drop mining skill, and attempt to get double drops when mining and wearing SlimeTinker armor.

**WHILE WEARING ARMOR PREVENTS THIS PICK (AND ANY OTHER) FROM GIVING DOUBLE DROPS**
[https://media.discordapp.net/attachments/915789505427034113/915796787472764978/2021-12-01_20.46.16.png?width=1114&height=590](url)

**ARMOR USED**
[https://cdn.discordapp.com/attachments/915789505427034113/915796718078033961/2021-12-01_20.43.43.png](url)

## Expected behavior (Required)

Regardless of the armor being worn, mcMMO double drops should not being impacted.

## Server Log / Error Report

N/A

## Environment (Required)

Paper git-Paper-388 (MC: 1.17.1)
Slimefun DEV - 986 (git 250fe4c9)
Metrics-Module #28
Java 16

Installed Addons: (23)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  CrystamaeHistoria vDEV - 15 (git 828f32cf)
  ExtraTools vDEV - 31 (git abdc1514)
  EcoPower vDEV - 5 (git 5c1ecd68)
  HotbarPets vDEV - 38 (git fa6c871d)
  SimpleMaterialGenerators v1.0.0
  DynaTech vDEV - 149 (git 4bd5aeef)
  ExtraGear vDEV - 13 (git c62047e2)
  HeadLimiter v22
  ExoticGarden vUNOFFICIAL
  InfinityExpansion vDEV - 125 (git 15a06ce6)
  CMILib v1.0.4.3
  SlimeCustomizer vDEV - 22 (git 7a62d8a7)
  SFCalc vDEV - 36 (git 74973a41)
  ExtraHeads vDEV - 23 (git 0b59a770)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  PrivateStorage vDEV - 18 (git 5832db21)
  FlowerPower vDEV - 10 (git 1beb0a87)
  SlimeTinker vDEV - 48 (git 02b06db0)
  TranscEndence vDEV - 39 (git cfb66ee5)
  SimpleStorage vDEV - 10 (git ea5e5637)
  FluffyMachines vDEV - 94 (git c5a76c49)

**Comment by iLuckyx** [comment]
Please note, this is the same issue we reported to you within the RoyaleMC community Discord. I just wanted to make it official with a bug report.

**Comment by Sefiraat** [comment]
Kinda forgot we resolved this! Call clooooooosed
